Sensors
COHRINT/minau pull request #2
Opened 2019-04-22 19:35 UTC by flamma7

2019-04-22 19:37 UTC, ianloefgren requested changes
Needs documentation!

2019-04-22 19:37 UTC, flamma7 commented
okay!

2019-04-24 15:39 UTC, ianloefgren commented
It would be helpful to explicitly declare a Depth message type, and rename Measurement.msg to something more  informative, like USBLMeasurement, or RangeAzEl, etc. to reduce confusion about what each message does. Otherwise, looks good.

2019-04-29 19:49 UTC, ianloefgren approved these changes

2019-04-29 19:49 UTC, merged